doc/api.rst
doc/example.rst
pandasdmx/model.py
pandasdmx/util.py
pandasdmx/writer.py
setup.py
tests/test_dataset.py
tests/test_model.py

Un-break builds & document unwrapping behaviour in to_pandas()

---

README.rst
doc/intro.rst

Link to v0.9 documentation from the README

---

pandasdmx/message.py
pandasdmx/util.py
tests/test_message.py

Pretty-print Message subclasses

---

pandasdmx/__init__.py
pandasdmx/api.py
tests/__init__.py
tests/test_api.py
tests/test_model.py

Convert Request.url() to a top-level convenience method

---

pandasdmx/__init__.py
pandasdmx/api.py
pandasdmx/model.py
pandasdmx/source/sgr.py
pandasdmx/source/wb.py
pandasdmx/util.py
tests/test_api.py
tests/test_sources.py

 Expand/clarify documentation for Request.get()

---

doc/howto.rst
doc/walkthrough.rst
pandasdmx/__init__.py
pandasdmx/api.py
tests/__init__.py
tests/test_api.py
tests/test_dataset.py
tests/test_dataset_bare.py
tests/test_dsd.py
tests/test_insee.py
tests/test_message.py
tests/test_reader_json.py
tests/test_reader_xml.py
tests/test_writer.py

Rename `open_file()` to `read_sdmx()`

---

pandasdmx/api.py
tests/test_api.py

Include Request convenience methods in interactive tab-completion

---

pandasdmx/api.py
pandasdmx/model.py
pandasdmx/reader/sdmxml.py
pandasdmx/source/istat.py
pandasdmx/sources.json
pandasdmx/util.py
tests/test_sources.py

Supply provider for ISTAT, improve SDMX-ML parser

---

pandasdmx/writer.py
tests/test_writer.py

Skip empty StructureMessage attributes in write_structuremessage

---

pandasdmx/sources.json
tests/test_api.py

Update tests for ECB, IMF data source changes

---

pandasdmx/model.py
pandasdmx/reader/__init__.py
pandasdmx/reader/sdmxjson.py
pandasdmx/reader/sdmxml.py
pandasdmx/remote.py
pandasdmx/source/__init__.py
pandasdmx/util.py
requirements.txt
setup.py
tests/test_api.py
tests/test_message.py
tests/test_model.py
tests/test_sources.py

- Closes #116 and updates to other changes introduced in pydantic 1.1 to 1.3.
- Encountered samuelcolvin/pydantic#1022; a fix was provided in samuelcolvin/pydantic#1023.

Re-sync with pydantic 1.1–1.3

---

.codecov.yml
doc/howto.rst
doc/walkthrough.rst
doc/whatsnew.rst
pandasdmx/model.py
pandasdmx/reader/sdmxml.py
pandasdmx/source/istat.py
pandasdmx/util.py
pandasdmx/writer.py
requirements.txt
tests/__init__.py
tests/data/demography/demography.xml
tests/data/demography/demography_xs.xml
tests/data/demography/esms.xml
tests/data/demography/esms_generic.xml
tests/data/demography/esms_structured.xml
tests/data/exr/common/exr_common.xml
tests/data/exr/ecb_exr_ng/ecb_exr_ng_full.xml
tests/data/exr/ecb_exr_rg/ecb_exr_rg_full.xml
tests/data/exr/ecb_exr_sg/ecb_exr_sg_full.xml
tests/test_dataset.py
tests/test_docs.py
tests/test_writer.py

 Provide features/examples for pd.DatetimeIndex etc. 

---

pandasdmx/model.py
tests/test_model.py

Closes #111 by fixing malformed docstrings and decreased test coverage introduced by #108.

Clean up #108

---

pandasdmx/remote.py
tests/test_docs.py

Closes #137 
TODO: update doc strings.

Improve remote.ResponseIO

---

.travis.yml

The tests pass without any changes to the test suite.

Activate Travis builds on osx, windows

---

README.rst

Also test that builds are triggered & reported to GitHub.

Update README badge/link from travis-ci.org -> .com

---

doc/example.rst
pandasdmx/api.py
pandasdmx/model.py
pandasdmx/tests/test_docs.py

Retain validation DSD for parsing; sort KeyValues while constructing Key

---

pandasdmx/api.py
pandasdmx/reader/sdmxml.py
pandasdmx/tests/data/IMF/ECOFIN_DSD-structure.xml
pandasdmx/tests/data/__init__.py
pandasdmx/tests/test_reader_xml.py
pandasdmx/tests/test_writer.py

Handle <com:Attribute> in <com:CubeRegion>

---

.gitignore
.travis.yml
README.rst
doc/example.rst
pandasdmx/api.py
pandasdmx/message.py
pandasdmx/tests/test_api.py
pandasdmx/tests/test_docs.py
pandasdmx/tests/test_writer.py

Extended writer tests. But this adds a log of duplication. Maybe check wrappers separately for efficiency.

Message: add to_pandas wrapper method and .write as alias for compat

---

doc/api.rst
doc/example.rst
doc/implementation.rst
doc/index.rst
doc/install.rst
doc/walkthrough.rst
doc/whatsnew.rst
pandasdmx/__init__.py
pandasdmx/api.py
pandasdmx/message.py
pandasdmx/tests/test_api.py
pandasdmx/tests/test_docs.py
pyproject.toml

Update docs, add test, minot improvements

Extend api.Request to use custom sessions

---

README.rst
doc/index.rst
doc/sources.rst
doc/whatsnew.rst
pandasdmx/__init__.py
pandasdmx/api.py
pandasdmx/sources.json

Update IMF source, bugfix for JSON data queries, bump to v1.0.1

---

pandasdmx/message.py

add missing import

---

.travis.yml
doc/index.rst
doc/sources.rst
doc/walkthrough.rst
doc/whatsnew.rst
pandasdmx/__init__.py
pandasdmx/api.py
pandasdmx/remote.py
pandasdmx/source/__init__.py
pandasdmx/sources.json
pandasdmx/tests/test_source.py
pyproject.toml

Py3.9 compat, add doc URLs to data sources, convenience method to Request
